5051/Controllers/KioskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _5051.Models;
using _5051.Backend;

namespace _5051.Controllers
{
    /// <summary>
    /// The Kiosk that will run in the classroom
    /// </summary>
    public class KioskController : Controller
    {
        // A ViewModel used for the Student that contains the StudentList
        private StudentViewModel StudentViewModel = new StudentViewModel();

        // The Backend Data source
        private StudentBackend StudentBackend = StudentBackend.Instance;

        /// <summary>
        /// Return the list of students with the status of logged in or out
        /// </summary>
        /// <returns></returns>
        // GET: Kiosk
        public ActionResult Index(int DisplayMsgType = 0)
        {
            var myDataList = StudentBackend.Index();
            var StudentViewModel = new StudentViewModel(myDataList);
            StudentViewModel.DisplayMsgType = DisplayMsgType;
            return View(StudentViewModel);
        }



        /// <summary>
        /// Landing page for admin to unlock the Kiosk
        /// </summary>
        /// <returns></returns>
        // GET: Kiosk/Landing
        public ActionResult Landing()
        {           
            return View(StudentViewModel);
        }

        /// <summary>
        /// Landing page for admin to unlock the Kiosk
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        // POST: Kiosk/Landing
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Landing(string passphase = "")
        {
            string valid = "schoolworks";
            if (passphase == "")
            {
                // Send to Error Page
                ModelState.AddModelError("Error", "Admin passphase does not match.");
                return View();
            }
            if(passphase == valid) {
                return RedirectToAction("Index");
            } else {

                ModelState.AddModelError("Error", "Admin passphase does not match.");
                return View();

            }
        }

        /// <summary>
        /// For students to create a new profile at the Kiosk
        /// </summary>
        /// <returns></returns>
        // GET: Kiosk/NewProfile
        public ActionResult NewProfile()
        {
            var myData = new StudentModel();
            return View(myData);
        }

        /// <summary>
        /// Make a new Student sent in by the create Student screen
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: Kiosk/NewProfile
        [HttpPost]
        public ActionResult NewProfile([Bind(Include=
                                        "Id,"+
                                        "Name,"+
                                        "Description,"+
                                        "Uri,"+
                                        "AvatarId,"+
                                        "Status,"+
                                        "")] StudentModel data)
        {
            if (!ModelState.IsValid)
            {
                // Send back for edit
                return View(data);
            }

            if (data == null)
            {
                // Send to Error Page
                return RedirectToAction("Error", new { route = "Home", action = "Error" });
            }

            if (string.IsNullOrEmpty(data.Id))
            {
                // Return back for Edit
                return View(data);
            }

            //Assign blank reports to a new student
            var Reports = StudentReportBackend.Instance.Index();
            var Report = Reports[Reports.Count - 1].Uri;
            data.ReportsId = Report;
            data.Status = StudentStatusEnum.In;

            StudentBackend.Create(data);
           
            return RedirectToAction("Index", new { DisplayMsgType = 1 });
            
        }

        // GET: Kiosk/SetLogin/5
        public ActionResult SetLogin(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Error","Home","Invalid Data");
            }

            StudentBackend.ToggleStatusById(id);
            StudentBackend.UpTokens(id, 100);
            return RedirectToAction("Index", new { DisplayMsgType = 2});
        }

        // GET: Kiosk/SetLogout/5
        public ActionResult SetLogout(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Error", "Home", "Invalid Data");
            }

            StudentBackend.ToggleStatusById(id);
            StudentBackend.UpTokens(id, 100);
            return RedirectToAction("Index", new { DisplayMsgType = 3});
        }
    }
}

5051/Controllers/PortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _5051.Controllers
{
    public class PortalController : Controller
    {
        /// <summary>
        /// The Login in page for the student portal, ask user for email and password
        /// </summary>
        /// <returns></returns>
        // GET: Portal
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// The Login in page for the Admin Portal
        /// </summary>
        /// <returns></returns>
        // GET: Portal
        public ActionResult AdminLogin()
        {
            return View();
        }

        /// <summary>
        /// Display logout page for the student portal
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            return View();
        }

        /// <summary>
        /// Index Page for student portal
        /// </summary>
        /// <returns></returns>
        // GET: Portal
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///  My Settings
        /// </summary>
        /// <returns></returns>
        // GET: Portal
        public ActionResult Settings()
        {
            return View();
        }
    }
}

5051/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nova Town Attendance Platform</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="icon" href="/Content/img/sitelogo.png">
</head>
<body>
    <header class="nav-wrapper">
        <nav class="navbar-custom">
            <div class="container-full">

                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar navbar-inverse navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bm-navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bm-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Student", "Login", "Portal")</li>
                        <li>@Html.ActionLink("Admin", "AdminLogin", "Portal")</li>
                        <li>@Html.ActionLink("Kiosk Mode", "Landing", "Kiosk")</li>
                        <li>@Html.ActionLink("Nova Town", "Index", "Home", new { area = "" }, new { @class = "navbar-brand hidden-xs" })</li>
                    </ul>
                </div><!-- End navbar-collapse -->

            </div><!-- End container -->
        </nav>
    </header>

    <div class="body-content">
        @RenderBody()
    </div>


    <!-- Footer -->

    <footer>
        <div class="footer">

            <div style="background-color: #5f5851;">

                <!-- Grid row-->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-12 text-center">
                        @Html.ActionLink("About", "About", "Home", new { controller = "Home" }, new { @class = "btn btn-link" }) &sdot;
                        @Html.ActionLink("Privacy Policy", "Privacy", "Home", new { controller = "Home" }, new { @class = "btn btn-link" }) &sdot;
                        @Html.ActionLink("Contact", "Contact", "Home", new { controller = "Home" }, new { @class = "btn btn-link" })
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p class="copyright text-muted small">&nbsp;&nbsp;&copy; @DateTime.Now.Year - Nova Town, all rights reserved. This website is made with <i class="fa fa-heart" aria-hidden="true"></i> by Fab5.</p>

                </div>
            </div>
        </div>
    </footer>

</body>
</html>